version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env

  web:
    build: .
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
               alembic upgrade head;
               uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - static_volume:/var/static
    ports:
      - 80:8000
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume:
